language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: GYkHWxGZbbzYBKgQonQexynRIqmIXgn1rdBX7XqZ5k67G98eSkmEc9tgGeQ2qPCdtwupJnDa5Dj03N2cz/ExPawjmCocptrPFQmjB2IhqyLtZ6xIVnIOItS31UaWOthbiuXOSfJn7UzkKECcAogCuT5v7U9G3GVNHvDZu7SbckSTEAKqS9tjkgTayIQw+oXoLFfxXMJ22uFKIcOne0iEL7VhXWM7Pde5cNOiqLtcE/1JW+qeS1Fjrn+xHorDTUT3oo30v3ERydiRuSf3g64ZDog2LyDw3vsbooBWulOgQhLxE0Ocr4HUok54RCEvdtvAoweygvNJR2fhlB7RmL6kXUd6uSNGf9WFNHUuSYMuCttrBsKg+A8GyY6CAcjYIV9kswwttcga9fFRZS44KMGNPBh7aEPfAiLxyDwsryCiDJ1yxG7jaFGDo3JdBTsnVZkAz6raP/DO6qPJxakY/3qXFBBKaWkYPf1yrF5d0puqkO/vCRI2toxIA5MZ8sR0K1F1RQH6mF0xGWKXAC4vM2VPV6bNfuPZqlJf6YQ8vxqCPXN4fqq2PH7rrPykQb0W/nJZnd5y8jMUhXWXbuHqUfXNJThgrLMsPA15uVqi15DPlhOwdRk3+hbyEeELJDPGOLhgfETY8ovBbh19aY9FjeAuZJrMCGvjMykzJ/K6Q7dv/cM=
    on_success: change
    on_pull_requests: false
install:
- npm install
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_success:
- npm run coveralls
- npm run semantic-release
after_script:
- greenkeeper-lockfile-upload
